name: Update Python Documentation

on:
  release:
    types: [created]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Prepare version
      run: |
        # get release version
        VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')

        # file and content that will be replaced
        PLACEHOLDER="release='default'"
        SETUP_FILE="docs/conf.py"

        # check to see that content is in file, then replace to have latest release version
        grep "${PLACEHOLDER}" "${SETUP_FILE}"
        sed -i "s/$PLACEHOLDER/release='${VERSION}'/g" ${SETUP_FILE}
    -
      name: Update Documentation
      run: |
        make --directory docs/ html
        git clone https://github.com/multicloud-ops/operator-csv-libs.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update operator csv libs documentation" -a || true
    -
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}