# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: login to artifactory
        run: echo "${{ secrets.ARTIFACTORY_TOKEN }}" | docker login hyc-cp4mcm-team-docker-local.artifactory.swg-devops.com -u "${{ secrets.ARTIFACTORY_USER }}" --password-stdin
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/ppc64le
          push: true
          tags: hyc-cp4mcm-team-docker-local.artifactory.swg-devops.com/cicd/python-environment:latest
