# This workflows will upload a python environment container to quay when there are changes to master
# For more information see: https://github.com/docker/build-push-action

name: Upload Python Environment Container to Quay

on:
  push:
    branches: master
  pull_request:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Prepare tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: quay.io/multicloudops/operator-csv-libs
          tag_with_sha: ${GITHUB_SHA::8}
      -
        name: output tag
        run: |
          echo ${{ steps.prepare.outputs.tag }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: login to quay
        run: |
          if [ ${{ github.event_name != 'pull_request' }} ]
          then
            echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u "${{ secrets.QUAY_USER }}" --password-stdin
          else
            echo "login skipped."
          fi
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64, linux/ppc64le
          push: false
          tags: |
            quay.io/multicloudops/operator-csv-libs:latest
            ${{ steps.prepare.outputs.tag }}
