name: Update Python Documentation

on:
  push

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    -
      name: Update Documentation
      run: |
        make --directory docs/ html
        git clone https://github.com/eveliososa/operator-csv-libs.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "evelio.sosa@ibm.com"
        git config --local user.name "Evelio Sosa"
        git add .
        git commit -m "update operator csv libs documentation" -a || true
        git push origin gh-pages