# This workflows will upload a python environment container to quay when there are changes to master
# For more information see: https://github.com/docker/build-push-action

name: Upload Python Environment Container to Quay

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Prepare tags
        id: prepare
        run: |
          DOCKER_IMAGE=quay.io/multicloudops/operator-csv-libs
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="${DOCKER_IMAGE}:${VERSION}"
            TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
      -
        name: Output tags
        run: |
          echo ${{ steps.prepare.outputs.tags }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: login to quay
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u "${{ secrets.QUAY_USER }}" --password-stdin
          else
            echo "login skipped"
          fi
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64, linux/ppc64le
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.prepare.outputs.tags }}
